apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ .Values.namespace }}"
  name: {{ include "imageapp.fullname" . }}
  labels:
    {{- include "imageapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "imageapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "imageapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.envs.FLASK_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.service.healthcheckPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.service.healthcheckPath }}
              port: http
          envFrom:
            - configMapRef:
                name: {{ include "imageapp.fullname" . }}
            # - secretRef:
            #     name: {{ include "imageapp.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
